# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26759ecf11166bb126e8e111d6dc04c7ba97cf2efe7092b546aadd2758aa59bbd8fb3d76f79d3999496cb3abaa6806a07e226a01a08e11bd8930e783e7e3e30e

test:
  secret_key_base: e459b3fff7b4e2fa12f3a248eb36f03540875619ed2e478db88ed990e67864eb1bd72f5ad6213054ec71d4920a07804cb94165c94d5be421219aa3a304b91cd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
